# This file must extend the project using templates
# The webDev class work perfectly, but need to add some featured


import os
import shutil


htmlStruct = """<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="some.ico" type="image/x-icon">
    <link href="style.css"></link>
    <title>Document</title>
</head>
<body>
    
<script src="script.js"></script>
</body>
</html>
"""


def removeAll(remove_settings=False):
    foldersInDir = os.listdir(os.getcwd())
    if len(os.listdir(os.getcwd())) > 1:
        for folder in foldersInDir:
            if remove_settings == False:
                if folder != 'settings.json':
                    if os.path.isdir(folder):
                        shutil.rmtree(folder)
                    else:
                        os.remove(folder)
            else:
                os.remove('settings.json')
    
        print('\033[32m' + 'Deleting was sucessful complete')
    else:
        print('\033[33m' + 'Nothing to delete')


class templateExpander():
    def __init__(self , args):
        self.args = args
        self.path = self.args['path']
        self.template = self.args['template']
        if 'github' in self.args:
            self.gitConnetcion = self.args['github']

    def understandSettings(self):
        # the folder of project
        if self.path == '.':
            self.folder = os.getcwd()
        else:
            self.folder = self.path

        if self.template == 'web':
            self.mainClass = webTemplate(self.path)
            self.mainClass.createElements()

        elif self.template == 'python':
            self.mainClass = pyTemplate(self.path)
            self.mainClass.createElements()
    

class webTemplate():
    def __init__(self , path):
        self.path = path
        self.homeFolder = os.getcwd() + '/'

    def createElements(self):
        self.folders = ['images' , 'src']
        self.files = ['src/index.html' , 'src/style.css' , 'src/script.js' , 'README.md']

        # create folders
        for folder in self.folders:
            if os.path.exists(self.homeFolder + folder) is False:
                os.mkdir(self.homeFolder + folder)
        
        # create files
        for file in self.files:
            if os.path.isfile(self.homeFolder + file) is False:
                os.mknod(self.homeFolder + file)
        
        self.prepareFiles()


    def prepareFiles(self):
        with open(self.homeFolder + '/README.md' , 'w') as file:
            file.write('# This is a basic readme file generated by TRIVVY')
        with open(self.homeFolder + '/src/index.html' , 'w') as file:
            file.write(htmlStruct)


class pyTemplate():
    def __init__(self , path):
        self.path = path
        self.homeFolder = os.getcwd() + '/'
    
    def createElements(self):
        self.folders = ['src/']
        self.files = ['src/__init__.py' , 'src/__main__.py' , 'README.md']
        for folder in self.folders:
            if os.path.exists(self.homeFolder + folder) == False:
                os.mkdir(self.homeFolder + folder)

        for file in self.files:
            if os.path.isfile(self.homeFolder + file) == False:
                os.mknod(self.homeFolder + file)
